[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "vault"

[dependencies]
IVault = { path = "../interface/IVault" }
IVaultACL = { path = "../interface/IVaultACL" }
